// Generates README.md, .claude-plugin/marketplace.json and site/data.json
// from data/mods.json + data/resolved.json. Offline and deterministic.
//
//   node scripts/build.mjs          # write files
//   node scripts/build.mjs --check  # fail if generated files are out of date
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { readJSON, config, TYPES, validateEntries, md, p } from "./lib.mjs";

const CHECK = process.argv.includes("--check");
const entries = readJSON("data/mods.json");
const resolved = readJSON("data/resolved.json", {});

const errors = validateEntries(entries);
if (errors.length) {
  console.error("data/mods.json has problems:\n  " + errors.join("\n  "));
  process.exit(1);
}

// ---- marketplace -----------------------------------------------------------
const used = new Map(); // plugin name -> entry id
const installOf = {};   // entry id -> [install ids]
const plugins = [];
for (const e of entries) {
  const r = e.bundle && resolved[e.id];
  if (!r) continue;
  installOf[e.id] = [];
  for (const pl of r.plugins) {
    // Claude Code reserves "claude-*" style plugin names for Anthropic, so strip the prefix
    // (or use the entry's explicit `rename` map) when we republish a third-party plugin.
    let name = e.rename?.[pl.name] ?? pl.name.replace(/^(claude|anthropic)s?-/i, "");
    if (used.has(name) && used.get(name) !== e.id) {
      name = `${pl.name}-${e.author.toLowerCase().replace(/[^a-z0-9._-]/g, "")}`;
    }
    used.set(name, e.id);
    installOf[e.id].push(name);
    plugins.push({
      name,
      source: pl.source,
      description: pl.description,
      author: { name: e.author, url: `https://github.com/${e.author}` },
      homepage: e.url,
      category: e.type,
      tags: e.tags || [],
      metadata: { entry: e.id, upstreamName: pl.name, upstreamMarketplace: r.upstreamMarketplace },
    });
  }
}
plugins.sort((a, b) => a.name.localeCompare(b.name));

const marketplace = {
  $schema: "https://json.schemastore.org/claude-code-marketplace.json",
  name: config.marketplaceName,
  description: `${config.siteName}: community Claude Code mods and plugins, each pinned to a reviewed commit.`,
  owner: config.owner,
  plugins,
};

const mk = config.marketplaceName;
const installLine = (e) =>
  installOf[e.id]?.length
    ? installOf[e.id].map((n) => `/plugin install ${n}@${mk}`)
    : e.install ? [e.install] : [];

// ---- README ------------------------------------------------------------------
const order = Object.keys(TYPES);
const byType = Object.fromEntries(order.map((t) => [t, entries.filter((e) => e.type === t)]));
const bundledCount = plugins.length;
const anchor = (t) => TYPES[t].label.toLowerCase().replace(/[^a-z0-9 -]/g, "").trim().replace(/ +/g, "-");

let readme = `<!-- Generated by scripts/build.mjs from data/mods.json. Do not edit by hand. -->
<div align="center">

# claudemods.chat

**${config.tagline}**

[Browse the site](${config.siteUrl}) · [Submit something](https://github.com/${config.repo}/issues/new?template=submit.yml) · [How it works](#how-it-works)

![entries](https://img.shields.io/badge/entries-${entries.length}-d97757) ![installable](https://img.shields.io/badge/installable_plugins-${bundledCount}-2f6f4f) ![license](https://img.shields.io/badge/list-CC0-lightgrey)

</div>

## Install everything from one place

Add the claudemods marketplace once, then install any mod by name:

\`\`\`
/plugin marketplace add ${config.repo}
/plugin install cc-arcade@${mk}
\`\`\`

Every plugin in the marketplace points at the exact upstream commit we looked at, so a mod can't change under you until we review and bump it.

> [!WARNING]
> Mods and plugins run with **your** permissions. They can read files, run commands and use the network. Read a mod's source before you install it.

## Contents

${order.filter((t) => byType[t].length).map((t) => `- [${TYPES[t].label}](#${anchor(t)}) (${byType[t].length})`).join("\n")}

`;

for (const t of order) {
  const list = byType[t];
  if (!list.length) continue;
  readme += `## ${TYPES[t].label}\n\n${TYPES[t].blurb}\n\n| Name | What it does | Install |\n| --- | --- | --- |\n`;
  const sorted = [...list].sort((a, b) => (b.featured ? 1 : 0) - (a.featured ? 1 : 0) || a.name.localeCompare(b.name));
  for (const e of sorted) {
    const inst = installLine(e);
    const cell = inst.length ? inst.map((i) => `\`${md(i)}\``).join("<br>") : "see repo";
    readme += `| [${md(e.name)}](${e.url})${e.featured ? " ⭐" : ""}<br><sub>by ${md(e.author)}</sub> | ${md(e.description)} | ${cell} |\n`;
  }
  readme += "\n";
}

readme += `## How it works

- \`data/mods.json\` is the only file people edit. One entry per mod, plugin, skill or link.
- \`scripts/sync.mjs\` reads each \`bundle: true\` entry's upstream \`.claude-plugin/marketplace.json\` (or \`plugin.json\`), pins it to the current commit and saves the result in \`data/resolved.json\`.
- \`scripts/build.mjs\` generates this README, \`.claude-plugin/marketplace.json\` and the site data.
- A weekly GitHub Action re-syncs and opens a pull request with any new commits, so every upstream change gets a human look before it reaches you.

## Contributing

The easiest way is the [submission form](https://github.com/${config.repo}/issues/new?template=submit.yml). A maintainer reviews it, labels it \`approved\`, and a bot opens the pull request for you. You can also edit \`data/mods.json\` directly; see [CONTRIBUTING.md](CONTRIBUTING.md).

## License

The list is [CC0](LICENSE). Each linked project keeps its own license.
`;

// ---- site data ----------------------------------------------------------------
const site = {
  siteName: config.siteName,
  repo: config.repo,
  marketplace: mk,
  types: Object.fromEntries(order.map((t) => [t, { ...TYPES[t], count: byType[t].length }])),
  entries: entries.map((e) => ({
    id: e.id, name: e.name, type: e.type, url: e.url, author: e.author,
    description: e.description, tags: e.tags || [], featured: !!e.featured,
    install: installLine(e), inMarketplace: !!installOf[e.id]?.length,
  })),
};

// ---- write / check ------------------------------------------------------------
const outputs = {
  "README.md": readme,
  ".claude-plugin/marketplace.json": JSON.stringify(marketplace, null, 2) + "\n",
  "site/data.json": JSON.stringify(site, null, 2) + "\n",
};

let stale = [];
for (const [file, content] of Object.entries(outputs)) {
  const current = existsSync(p(file)) ? readFileSync(p(file), "utf8") : null;
  if (current === content) continue;
  if (CHECK) stale.push(file);
  else {
    mkdirSync(p(file, ".."), { recursive: true });
    writeFileSync(p(file), content);
    console.log(`wrote ${file}`);
  }
}
if (CHECK && stale.length) {
  console.error(`Out of date: ${stale.join(", ")}. Run: node scripts/build.mjs`);
  process.exit(1);
}
console.log(`${entries.length} entries, ${plugins.length} installable plugins in "${mk}".`);
