// Generates README.md, .claude-plugin/marketplace.json and the site (index.html
// from scripts/index.template.html, data.json, robots.txt, sitemap.xml)
// from data/mods.json + data/resolved.json. Offline and deterministic.
//
//   node scripts/build.mjs          # write files
//   node scripts/build.mjs --check  # fail if generated files are out of date
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { readJSON, config, TYPES, FLAGS, validateEntries, policyErrors, md, p } from "./lib.mjs";
import { pluginLocation } from "./footprint.mjs";

const CHECK = process.argv.includes("--check");
const entries = readJSON("data/mods.json");
const resolved = readJSON("data/resolved.json", {});

const errors = validateEntries(entries);
for (const e of entries) if (e.bundle && resolved[e.id]) errors.push(...policyErrors(e, resolved[e.id]));
if (errors.length) {
  console.error("data/ has problems:\n  " + errors.join("\n  "));
  process.exit(1);
}

// ---- marketplace -----------------------------------------------------------
const used = new Map(); // plugin name -> entry id
const installOf = {};   // entry id -> [install ids]
const pluginsOf = {};   // entry id -> [{ name, description, footprint, loc }] for the site
const plugins = [];
for (const e of entries) {
  const r = e.bundle && resolved[e.id];
  if (!r) continue;
  installOf[e.id] = [];
  pluginsOf[e.id] = [];
  for (const pl of r.plugins) {
    // Claude Code reserves "claude-*" style plugin names for Anthropic, so strip the prefix
    // (or use the entry's explicit `rename` map) when we republish a third-party plugin.
    let name = e.rename?.[pl.name] ?? pl.name.replace(/^(claude|anthropic)s?-/i, "");
    if (used.has(name) && used.get(name) !== e.id) {
      name = `${pl.name}-${e.author.toLowerCase().replace(/[^a-z0-9._-]/g, "")}`;
    }
    used.set(name, e.id);
    installOf[e.id].push(name);
    pluginsOf[e.id].push({ name, description: pl.description || "", footprint: pl.footprint, loc: pluginLocation(pl) });
    plugins.push({
      name,
      source: pl.source,
      description: pl.description,
      author: { name: e.author, url: `https://github.com/${e.author}` },
      homepage: e.url,
      category: e.type,
      tags: e.tags || [],
      metadata: { entry: e.id, upstreamName: pl.name, upstreamMarketplace: r.upstreamMarketplace },
    });
  }
}
plugins.sort((a, b) => a.name.localeCompare(b.name));

const marketplace = {
  $schema: "https://json.schemastore.org/claude-code-marketplace.json",
  name: config.marketplaceName,
  description: `${config.siteName}: community Claude Code mods and plugins, each pinned to a reviewed commit.`,
  owner: config.owner,
  plugins,
};

const mk = config.marketplaceName;
const installLine = (e) =>
  installOf[e.id]?.length
    ? installOf[e.id].map((n) => `/plugin install ${n}@${mk}`)
    : e.install ? [e.install] : [];

// ---- README ------------------------------------------------------------------
const order = Object.keys(TYPES);
const byType = Object.fromEntries(order.map((t) => [t, entries.filter((e) => e.type === t)]));
const bundledCount = plugins.length;
const anchor = (t) => TYPES[t].label.toLowerCase().replace(/[^a-z0-9 -]/g, "").trim().replace(/ +/g, "-");
const featuredFirst = (list) => [...list].sort((a, b) => (b.featured ? 1 : 0) - (a.featured ? 1 : 0) || a.name.localeCompare(b.name));

let readme = `<!-- Generated by scripts/build.mjs from data/mods.json. Do not edit by hand. -->
<div align="center">

# claudemods.chat

**${config.tagline}**

[Browse the site](${config.siteUrl}) · [Submit something](https://github.com/${config.repo}/issues/new?template=submit.yml) · [How it works](#how-it-works)

![entries](https://img.shields.io/badge/entries-${entries.length}-d97757) ![installable](https://img.shields.io/badge/installable_plugins-${bundledCount}-2f6f4f) ![license](https://img.shields.io/badge/list-CC0-lightgrey)

</div>

## Install everything from one place

Add the claudemods marketplace once, then install any mod by name:

\`\`\`
/plugin marketplace add ${config.repo}
/plugin install cc-arcade@${mk}
\`\`\`

Every plugin in the marketplace points at the exact upstream commit we looked at, so a mod can't change under you until we review and bump it.

> [!WARNING]
> Mods and plugins run with **your** permissions. They can read files, run commands and use the network. Read a mod's source before you install it.

## Contents

${order.filter((t) => byType[t].length).map((t) => `- [${TYPES[t].label}](#${anchor(t)}) (${byType[t].length})`).join("\n")}

`;

for (const t of order) {
  const list = byType[t];
  if (!list.length) continue;
  readme += `## ${TYPES[t].label}\n\n${TYPES[t].blurb}\n\n| Name | What it does | Install |\n| --- | --- | --- |\n`;
  for (const e of featuredFirst(list)) {
    const inst = installLine(e);
    const cell = inst.length ? inst.map((i) => `\`${md(i)}\``).join("<br>") : "see repo";
    readme += `| [${md(e.name)}](${e.url})${e.featured ? " ⭐" : ""}<br><sub>by ${md(e.author)}</sub> | ${md(e.description)} | ${cell} |\n`;
  }
  readme += "\n";
}

readme += `## How it works

- \`data/mods.json\` is the only file people edit. One entry per mod, plugin, skill or link.
- \`scripts/sync.mjs\` reads each \`bundle: true\` entry's upstream \`.claude-plugin/marketplace.json\` (or \`plugin.json\`), pins it to the current commit and saves the result in \`data/resolved.json\`.
- \`scripts/build.mjs\` generates this README, \`.claude-plugin/marketplace.json\` and the site.
- \`scripts/footprint.mjs\` reads every bundled plugin at its pinned commit and records what it runs: shell hooks, function-hook modules and the \`$\` calls they make, MCP servers, plus flags such as network access, running programs, touching credentials or skipping permission prompts. The site shows it on every card. A plugin that fetches code at runtime isn't bundled unless its entry says why (\`acknowledge\`).
- A weekly GitHub Action re-syncs and opens a pull request with any new commits and what changed in what each plugin runs, so every upstream change gets a human look before it reaches you. Another installs every plugin into a clean config each week.

## Contributing

The easiest way is the [submission form](https://github.com/${config.repo}/issues/new?template=submit.yml). A maintainer reviews it, labels it \`approved\`, and a bot opens the pull request for you. You can also edit \`data/mods.json\` directly; see [CONTRIBUTING.md](CONTRIBUTING.md).

## License

The list is [CC0](LICENSE). Each linked project keeps its own license.
`;

// ---- site data ----------------------------------------------------------------
const site = {
  siteName: config.siteName,
  repo: config.repo,
  marketplace: mk,
  types: Object.fromEntries(order.map((t) => [t, { ...TYPES[t], count: byType[t].length }])),
  entries: entries.map((e) => ({
    id: e.id, name: e.name, type: e.type, url: e.url, author: e.author,
    description: e.description, tags: e.tags || [], featured: !!e.featured,
    install: installLine(e), inMarketplace: !!installOf[e.id]?.length,
    ...(pluginsOf[e.id] ? { plugins: pluginsOf[e.id].map((pl) => ({
      name: pl.name, install: `/plugin install ${pl.name}@${mk}`, description: pl.description,
      source: pl.loc && { repo: pl.loc.repo, sha: pl.loc.sha, path: pl.loc.root }, footprint: pl.footprint,
    })) } : {}),
    ...(e.acknowledge ? { acknowledge: e.acknowledge } : {}),
  })),
};

// ---- site page ----------------------------------------------------------------
// Every entry is rendered into the HTML so search engines (and readers without
// JavaScript) see the whole directory; the page's script only filters and sorts.
const html = (s) => String(s ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
const siteUrl = config.siteUrl.replace(/\/?$/, "/");
const repoUrl = `https://github.com/${config.repo}`;
const submitUrl = `${repoUrl}/issues/new?template=submit.yml`;
const title = "Claude Mods – Claude Code mods, plugins & skills directory";
const description = `Browse ${entries.length} Claude mods, plugins, skills, hooks, status lines and MCP servers for Claude Code. Install ${bundledCount} of them from one marketplace.`;
const shownTypes = order.filter((t) => byType[t].length);
const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

// ---- what a plugin runs (footprint from scripts/footprint.mjs) ----
const short = (s, n) => (s.length > n ? s.slice(0, n - 1) + "…" : s);
const plural = (n, w) => `${n} ${w}${n === 1 ? "" : "s"}`;
const LEVEL_ORDER = { bad: 0, warn: 1, info: 2, ok: 3 };
function runsChips(fp) {
  const chips = [];
  if (!fp.hooks.length && !fp.modules.length && !fp.mcp.length) chips.push(["ok", "Prompts only"]);
  if (fp.hooks.length) {
    const ev = [...new Set(fp.hooks.map((h) => h.event))];
    chips.push(["warn", `Shell hooks: ${ev.slice(0, 2).join(", ")}${ev.length > 2 ? ` +${ev.length - 2}` : ""}`]);
  }
  if (fp.modules.length) chips.push(["warn", "Runs code inside Claude Code"]);
  if (fp.mcp.some((m) => !m.url)) chips.push(["warn", "Local MCP server"]);
  for (const host of new Set(fp.mcp.filter((m) => m.url).map((m) => new URL(m.url).hostname))) chips.push(["info", `Talks to ${host}`]);
  for (const f of fp.flags) {
    if (f.id === "network" && f.where.every((w) => w.startsWith("mcp:"))) continue; // already a "Talks to" chip
    chips.push([FLAGS[f.id].level, FLAGS[f.id].label]);
  }
  return chips.sort((a, b) => LEVEL_ORDER[a[0]] - LEVEL_ORDER[b[0]]);
}
function runsDetails(pl, e) {
  const { footprint: fp, loc } = pl;
  const at = (path) => `https://github.com/${loc.repo}/blob/${loc.sha}/${loc.root ? loc.root + "/" : ""}${path}`;
  const where = (w) => (/^(?:hook|mcp):/.test(w) ? html(w) : `<a href="${html(at(w))}" target="_blank" rel="noopener">${html(w)}</a>`);
  const ships = [fp.skills && plural(fp.skills, "skill"), fp.commands && plural(fp.commands, "command"), fp.agents && plural(fp.agents, "agent")].filter(Boolean).join(", ");
  const out = [`<p>Read from <a href="https://github.com/${html(loc.repo)}/tree/${loc.sha}${loc.root ? "/" + html(loc.root) : ""}" target="_blank" rel="noopener">${html(loc.repo)}@${loc.sha.slice(0, 7)}</a>, the commit this install is pinned to${ships ? `. Ships ${ships}` : ""}.</p>`];
  if (fp.hooks.length) out.push(`<p class="fp-h">Shell hooks</p><ul>${fp.hooks.map((h) => `<li><b>${html(h.event)}</b>${h.matcher ? ` <span class="fp-m">${html(h.matcher)}</span>` : ""}<code>${html(short(h.command, 240))}</code></li>`).join("")}</ul>`);
  if (fp.modules.length) out.push(`<p class="fp-h">Code inside Claude Code</p><ul><li>Modules: ${fp.modules.map((m) => `<code>${html(m)}</code>`).join(" ")}</li>`
    + (fp.events ? `<li>Hooks: ${html(fp.events.join(", "))}</li>` : "") + (fp.calls ? `<li>Uses: ${html(fp.calls.map((c) => "$." + c).join(", "))}</li>` : "") + (fp.env ? `<li>Reads env: ${html(fp.env.join(", "))}</li>` : "") + "</ul>");
  if (fp.mcp.length) out.push(`<p class="fp-h">MCP servers</p><ul>${fp.mcp.map((m) => `<li><b>${html(m.name)}</b><code>${html(short(m.url || m.command, 240))}</code></li>`).join("")}</ul>`);
  if (fp.flags.length) out.push(`<p class="fp-h">Flags</p><ul>${fp.flags.map((f) => `<li><span class="rk lv-${FLAGS[f.id].level}">${html(FLAGS[f.id].label)}</span> ${f.where.map(where).join(", ")}${f.more ? ` and ${f.more} more` : ""}`
    + (f.via ? `<code>${html(f.via.join("  ·  "))}</code>` : "") + (f.hosts ? `<span class="fp-m">hosts: ${html(f.hosts.join(", "))}</span>` : "")
    + (e.acknowledge?.[f.id] ? `<em>Reviewed: ${html(e.acknowledge[f.id])}</em>` : "") + "</li>").join("")}</ul>`);
  out.push(`<p class="fp-note">Flags are pattern matches: a reason to read the code, not a verdict.</p>`);
  return out.join("");
}

function card(e) {
  const row = (i) =>
    `<div class="install-row"><code title="${html(i)}">${html(i)}</code><button class="copy" data-copy="${html(i)}" aria-label="Copy install command"></button></div>`;
  const block = (pl, multi) => {
    const chips = runsChips(pl.footprint);
    return `<div class="plugin">${row(`/plugin install ${pl.name}@${mk}`)}`
      + (multi && pl.description ? `<p class="pdesc" title="${html(pl.description)}">${html(short(pl.description, 160))}</p>` : "")
      + `<details class="fp"><summary>${chips.slice(0, 4).map(([lv, t]) => `<span class="rk lv-${lv}">${html(t)}</span>`).join("")}`
      + `${chips.length > 4 ? `<span class="rk">+${chips.length - 4}</span>` : ""}<span class="fp-more">What it runs</span></summary><div class="fp-body">${runsDetails(pl, e)}</div></details></div>`;
  };
  // One plugin on the card; the rest fold away so a big bundle doesn't stretch its whole grid row.
  const pls = pluginsOf[e.id] || [];
  const [first, ...rest] = pls;
  const rows = first
    ? block(first, pls.length > 1) + (rest.length ? `<details class="more"><summary>+${rest.length} more plugin${rest.length > 1 ? "s" : ""}</summary>${rest.map((pl) => block(pl, true)).join("")}</details>` : "")
    : e.install ? `${row(e.install)}<p class="ext">Installs from upstream: not pinned or scanned by claudemods.</p>` : "";
  const badge = TYPES[e.type].label.replace(/s$/, "").replace(/ & .*/, "");
  return `<article class="card" id="${html(e.id)}" data-type="${e.type}">
        <div class="card-head"><div><h3><a href="${html(e.url)}" target="_blank" rel="noopener">${html(e.name)}</a>${e.featured ? " ⭐" : ""}</h3>
          <div class="by">by <a href="https://github.com/${html(e.author)}" target="_blank" rel="noopener">${html(e.author)}</a></div></div>
          <span class="badge${e.type === "mod" ? " mod" : ""}">${html(badge)}</span></div>
        <p class="desc">${html(e.description)}</p>
        <div class="tags">${(e.tags || []).map((t) => `<span class="tag">${html(t)}</span>`).join("")}</div>
        <div class="install">${installOf[e.id]?.length ? '<span class="mk">In the claudemods marketplace</span>' : ""}${rows || `<a class="by" href="${html(e.url)}" target="_blank" rel="noopener">See the repo for setup →</a>`}</div>
      </article>`;
}

const directory = shownTypes.map((t) => `    <section class="group" id="${slug(TYPES[t].heading)}">
      <h2>${html(TYPES[t].heading)}</h2>
      <p>${html(TYPES[t].blurb)}</p>
      <div class="grid">
      ${featuredFirst(byType[t]).map(card).join("\n      ")}
      </div>
    </section>`).join("\n");

const chips = [`<button class="chip" data-type="all" aria-pressed="true">All<span>${entries.length}</span></button>`]
  .concat(shownTypes.map((t) => `<button class="chip" data-type="${t}" aria-pressed="false">${html(TYPES[t].label)}<span>${byType[t].length}</span></button>`))
  .join("");

// JSON-LD: what the site is, plus the entries as an ItemList pointing at their cards.
const jsonLd = JSON.stringify({
  "@context": "https://schema.org",
  "@graph": [
    { "@type": "WebSite", "@id": `${siteUrl}#website`, name: config.siteName, alternateName: "Claude Mods", url: siteUrl, description },
    {
      "@type": "CollectionPage", "@id": `${siteUrl}#page`, url: siteUrl, name: title, description, isPartOf: { "@id": `${siteUrl}#website` },
      mainEntity: {
        "@type": "ItemList", numberOfItems: entries.length,
        itemListElement: shownTypes.flatMap((t) => featuredFirst(byType[t])).map((e, i) => ({ "@type": "ListItem", position: i + 1, name: e.name, url: `${siteUrl}#${e.id}` })),
      },
    },
  ],
}).replace(/</g, "\\u003c");

const head = [
  `<title>${html(title)}</title>`,
  `<meta name="description" content="${html(description)}">`,
  `<link rel="canonical" href="${siteUrl}">`,
  `<meta name="theme-color" content="#c4623f">`,
  `<meta property="og:type" content="website">`,
  `<meta property="og:site_name" content="${html(config.siteName)}">`,
  `<meta property="og:url" content="${siteUrl}">`,
  `<meta property="og:title" content="${html(title)}">`,
  `<meta property="og:description" content="${html(description)}">`,
  `<meta property="og:image" content="${siteUrl}og.png">`,
  `<meta property="og:image:width" content="1200">`,
  `<meta property="og:image:height" content="630">`,
  `<meta property="og:image:alt" content="claudemods.chat: Claude mods, plugins and skills in one marketplace">`,
  `<meta name="twitter:card" content="summary_large_image">`,
  `<script type="application/ld+json">${jsonLd}</script>`,
].join("\n");

const pageVars = {
  head, directory, chips,
  stats: `<span><b>${byType.mod.length}</b> mods</span><span><b>${bundledCount}</b> one-command installs</span><span><b>${entries.length}</b> entries</span>`,
  count: entries.length, repo: html(config.repo), marketplace: html(mk), repoUrl: html(repoUrl), submitUrl: html(submitUrl),
};
const page = readFileSync(p("scripts/index.template.html"), "utf8").replace(/\{\{(\w+)\}\}/g, (m, k) => {
  if (!(k in pageVars)) throw new Error(`unknown placeholder ${m} in scripts/index.template.html`);
  return pageVars[k];
});

const lastmod = entries.map((e) => e.added).filter(Boolean).sort().pop();
const robots = `User-agent: *\nAllow: /\n\nSitemap: ${siteUrl}sitemap.xml\n`;
const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url><loc>${siteUrl}</loc>${lastmod ? `<lastmod>${lastmod}</lastmod>` : ""}</url>
</urlset>
`;

// ---- write / check ------------------------------------------------------------
const outputs = {
  "README.md": readme,
  ".claude-plugin/marketplace.json": JSON.stringify(marketplace, null, 2) + "\n",
  "site/data.json": JSON.stringify(site, null, 2) + "\n",
  "site/index.html": page,
  "site/robots.txt": robots,
  "site/sitemap.xml": sitemap,
};

let stale = [];
for (const [file, content] of Object.entries(outputs)) {
  const current = existsSync(p(file)) ? readFileSync(p(file), "utf8") : null;
  if (current === content) continue;
  if (CHECK) stale.push(file);
  else {
    mkdirSync(p(file, ".."), { recursive: true });
    writeFileSync(p(file), content);
    console.log(`wrote ${file}`);
  }
}
if (CHECK && stale.length) {
  console.error(`Out of date: ${stale.join(", ")}. Run: node scripts/build.mjs`);
  process.exit(1);
}
console.log(`${entries.length} entries, ${plugins.length} installable plugins in "${mk}".`);
