// Generates README.md, .claude-plugin/marketplace.json and the site (index.html
// from scripts/index.template.html, data.json, robots.txt, sitemap.xml)
// from data/mods.json + data/resolved.json. Offline and deterministic.
//
//   node scripts/build.mjs          # write files
//   node scripts/build.mjs --check  # fail if generated files are out of date
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { readJSON, config, TYPES, validateEntries, md, p } from "./lib.mjs";

const CHECK = process.argv.includes("--check");
const entries = readJSON("data/mods.json");
const resolved = readJSON("data/resolved.json", {});

const errors = validateEntries(entries);
if (errors.length) {
  console.error("data/mods.json has problems:\n  " + errors.join("\n  "));
  process.exit(1);
}

// ---- marketplace -----------------------------------------------------------
const used = new Map(); // plugin name -> entry id
const installOf = {};   // entry id -> [install ids]
const plugins = [];
for (const e of entries) {
  const r = e.bundle && resolved[e.id];
  if (!r) continue;
  installOf[e.id] = [];
  for (const pl of r.plugins) {
    // Claude Code reserves "claude-*" style plugin names for Anthropic, so strip the prefix
    // (or use the entry's explicit `rename` map) when we republish a third-party plugin.
    let name = e.rename?.[pl.name] ?? pl.name.replace(/^(claude|anthropic)s?-/i, "");
    if (used.has(name) && used.get(name) !== e.id) {
      name = `${pl.name}-${e.author.toLowerCase().replace(/[^a-z0-9._-]/g, "")}`;
    }
    used.set(name, e.id);
    installOf[e.id].push(name);
    plugins.push({
      name,
      source: pl.source,
      description: pl.description,
      author: { name: e.author, url: `https://github.com/${e.author}` },
      homepage: e.url,
      category: e.type,
      tags: e.tags || [],
      metadata: { entry: e.id, upstreamName: pl.name, upstreamMarketplace: r.upstreamMarketplace },
    });
  }
}
plugins.sort((a, b) => a.name.localeCompare(b.name));

const marketplace = {
  $schema: "https://json.schemastore.org/claude-code-marketplace.json",
  name: config.marketplaceName,
  description: `${config.siteName}: community Claude Code mods and plugins, each pinned to a reviewed commit.`,
  owner: config.owner,
  plugins,
};

const mk = config.marketplaceName;
const installLine = (e) =>
  installOf[e.id]?.length
    ? installOf[e.id].map((n) => `/plugin install ${n}@${mk}`)
    : e.install ? [e.install] : [];

// ---- README ------------------------------------------------------------------
const order = Object.keys(TYPES);
const byType = Object.fromEntries(order.map((t) => [t, entries.filter((e) => e.type === t)]));
const bundledCount = plugins.length;
const anchor = (t) => TYPES[t].label.toLowerCase().replace(/[^a-z0-9 -]/g, "").trim().replace(/ +/g, "-");
const featuredFirst = (list) => [...list].sort((a, b) => (b.featured ? 1 : 0) - (a.featured ? 1 : 0) || a.name.localeCompare(b.name));

let readme = `<!-- Generated by scripts/build.mjs from data/mods.json. Do not edit by hand. -->
<div align="center">

# claudemods.chat

**${config.tagline}**

[Browse the site](${config.siteUrl}) · [Submit something](https://github.com/${config.repo}/issues/new?template=submit.yml) · [How it works](#how-it-works)

![entries](https://img.shields.io/badge/entries-${entries.length}-d97757) ![installable](https://img.shields.io/badge/installable_plugins-${bundledCount}-2f6f4f) ![license](https://img.shields.io/badge/list-CC0-lightgrey)

</div>

## Install everything from one place

Add the claudemods marketplace once, then install any mod by name:

\`\`\`
/plugin marketplace add ${config.repo}
/plugin install cc-arcade@${mk}
\`\`\`

Every plugin in the marketplace points at the exact upstream commit we looked at, so a mod can't change under you until we review and bump it.

> [!WARNING]
> Mods and plugins run with **your** permissions. They can read files, run commands and use the network. Read a mod's source before you install it.

## Contents

${order.filter((t) => byType[t].length).map((t) => `- [${TYPES[t].label}](#${anchor(t)}) (${byType[t].length})`).join("\n")}

`;

for (const t of order) {
  const list = byType[t];
  if (!list.length) continue;
  readme += `## ${TYPES[t].label}\n\n${TYPES[t].blurb}\n\n| Name | What it does | Install |\n| --- | --- | --- |\n`;
  for (const e of featuredFirst(list)) {
    const inst = installLine(e);
    const cell = inst.length ? inst.map((i) => `\`${md(i)}\``).join("<br>") : "see repo";
    readme += `| [${md(e.name)}](${e.url})${e.featured ? " ⭐" : ""}<br><sub>by ${md(e.author)}</sub> | ${md(e.description)} | ${cell} |\n`;
  }
  readme += "\n";
}

readme += `## How it works

- \`data/mods.json\` is the only file people edit. One entry per mod, plugin, skill or link.
- \`scripts/sync.mjs\` reads each \`bundle: true\` entry's upstream \`.claude-plugin/marketplace.json\` (or \`plugin.json\`), pins it to the current commit and saves the result in \`data/resolved.json\`.
- \`scripts/build.mjs\` generates this README, \`.claude-plugin/marketplace.json\` and the site.
- A weekly GitHub Action re-syncs and opens a pull request with any new commits, so every upstream change gets a human look before it reaches you.

## Contributing

The easiest way is the [submission form](https://github.com/${config.repo}/issues/new?template=submit.yml). A maintainer reviews it, labels it \`approved\`, and a bot opens the pull request for you. You can also edit \`data/mods.json\` directly; see [CONTRIBUTING.md](CONTRIBUTING.md).

## License

The list is [CC0](LICENSE). Each linked project keeps its own license.
`;

// ---- site data ----------------------------------------------------------------
const site = {
  siteName: config.siteName,
  repo: config.repo,
  marketplace: mk,
  types: Object.fromEntries(order.map((t) => [t, { ...TYPES[t], count: byType[t].length }])),
  entries: entries.map((e) => ({
    id: e.id, name: e.name, type: e.type, url: e.url, author: e.author,
    description: e.description, tags: e.tags || [], featured: !!e.featured,
    install: installLine(e), inMarketplace: !!installOf[e.id]?.length,
  })),
};

// ---- site page ----------------------------------------------------------------
// Every entry is rendered into the HTML so search engines (and readers without
// JavaScript) see the whole directory; the page's script only filters and sorts.
const html = (s) => String(s ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
const siteUrl = config.siteUrl.replace(/\/?$/, "/");
const repoUrl = `https://github.com/${config.repo}`;
const submitUrl = `${repoUrl}/issues/new?template=submit.yml`;
const title = "Claude Mods – Claude Code mods, plugins & skills directory";
const description = `Browse ${entries.length} Claude mods, plugins, skills, hooks, status lines and MCP servers for Claude Code. Install ${bundledCount} of them from one marketplace.`;
const shownTypes = order.filter((t) => byType[t].length);
const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

function card(e) {
  const inst = installLine(e);
  const row = (i) =>
    `<div class="install-row"><code title="${html(i)}">${html(i)}</code><button class="copy" data-copy="${html(i)}" aria-label="Copy install command"></button></div>`;
  // One command on the card; the rest fold away so a big bundle doesn't stretch its whole grid row.
  const [first, ...rest] = inst;
  const rows = (first ? row(first) : "")
    + (rest.length ? `<details class="more"><summary>+${rest.length} more plugin${rest.length > 1 ? "s" : ""}</summary>${rest.map(row).join("")}</details>` : "");
  const badge = TYPES[e.type].label.replace(/s$/, "").replace(/ & .*/, "");
  return `<article class="card" id="${html(e.id)}" data-type="${e.type}">
        <div class="card-head"><div><h3><a href="${html(e.url)}" target="_blank" rel="noopener">${html(e.name)}</a>${e.featured ? " ⭐" : ""}</h3>
          <div class="by">by <a href="https://github.com/${html(e.author)}" target="_blank" rel="noopener">${html(e.author)}</a></div></div>
          <span class="badge${e.type === "mod" ? " mod" : ""}">${html(badge)}</span></div>
        <p class="desc">${html(e.description)}</p>
        <div class="tags">${(e.tags || []).map((t) => `<span class="tag">${html(t)}</span>`).join("")}</div>
        <div class="install">${installOf[e.id]?.length ? '<span class="mk">In the claudemods marketplace</span>' : ""}${rows || `<a class="by" href="${html(e.url)}" target="_blank" rel="noopener">See the repo for setup →</a>`}</div>
      </article>`;
}

const directory = shownTypes.map((t) => `    <section class="group" id="${slug(TYPES[t].heading)}">
      <h2>${html(TYPES[t].heading)}</h2>
      <p>${html(TYPES[t].blurb)}</p>
      <div class="grid">
      ${featuredFirst(byType[t]).map(card).join("\n      ")}
      </div>
    </section>`).join("\n");

const chips = [`<button class="chip" data-type="all" aria-pressed="true">All<span>${entries.length}</span></button>`]
  .concat(shownTypes.map((t) => `<button class="chip" data-type="${t}" aria-pressed="false">${html(TYPES[t].label)}<span>${byType[t].length}</span></button>`))
  .join("");

// JSON-LD: what the site is, plus the entries as an ItemList pointing at their cards.
const jsonLd = JSON.stringify({
  "@context": "https://schema.org",
  "@graph": [
    { "@type": "WebSite", "@id": `${siteUrl}#website`, name: config.siteName, alternateName: "Claude Mods", url: siteUrl, description },
    {
      "@type": "CollectionPage", "@id": `${siteUrl}#page`, url: siteUrl, name: title, description, isPartOf: { "@id": `${siteUrl}#website` },
      mainEntity: {
        "@type": "ItemList", numberOfItems: entries.length,
        itemListElement: shownTypes.flatMap((t) => featuredFirst(byType[t])).map((e, i) => ({ "@type": "ListItem", position: i + 1, name: e.name, url: `${siteUrl}#${e.id}` })),
      },
    },
  ],
}).replace(/</g, "\\u003c");

const head = [
  `<title>${html(title)}</title>`,
  `<meta name="description" content="${html(description)}">`,
  `<link rel="canonical" href="${siteUrl}">`,
  `<meta name="theme-color" content="#c4623f">`,
  `<meta property="og:type" content="website">`,
  `<meta property="og:site_name" content="${html(config.siteName)}">`,
  `<meta property="og:url" content="${siteUrl}">`,
  `<meta property="og:title" content="${html(title)}">`,
  `<meta property="og:description" content="${html(description)}">`,
  `<meta property="og:image" content="${siteUrl}og.png">`,
  `<meta property="og:image:width" content="1200">`,
  `<meta property="og:image:height" content="630">`,
  `<meta property="og:image:alt" content="claudemods.chat: Claude mods, plugins and skills in one marketplace">`,
  `<meta name="twitter:card" content="summary_large_image">`,
  `<script type="application/ld+json">${jsonLd}</script>`,
].join("\n");

const pageVars = {
  head, directory, chips,
  stats: `<span><b>${byType.mod.length}</b> mods</span><span><b>${bundledCount}</b> one-command installs</span><span><b>${entries.length}</b> entries</span>`,
  count: entries.length, repo: html(config.repo), marketplace: html(mk), repoUrl: html(repoUrl), submitUrl: html(submitUrl),
};
const page = readFileSync(p("scripts/index.template.html"), "utf8").replace(/\{\{(\w+)\}\}/g, (m, k) => {
  if (!(k in pageVars)) throw new Error(`unknown placeholder ${m} in scripts/index.template.html`);
  return pageVars[k];
});

const lastmod = entries.map((e) => e.added).filter(Boolean).sort().pop();
const robots = `User-agent: *\nAllow: /\n\nSitemap: ${siteUrl}sitemap.xml\n`;
const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url><loc>${siteUrl}</loc>${lastmod ? `<lastmod>${lastmod}</lastmod>` : ""}</url>
</urlset>
`;

// ---- write / check ------------------------------------------------------------
const outputs = {
  "README.md": readme,
  ".claude-plugin/marketplace.json": JSON.stringify(marketplace, null, 2) + "\n",
  "site/data.json": JSON.stringify(site, null, 2) + "\n",
  "site/index.html": page,
  "site/robots.txt": robots,
  "site/sitemap.xml": sitemap,
};

let stale = [];
for (const [file, content] of Object.entries(outputs)) {
  const current = existsSync(p(file)) ? readFileSync(p(file), "utf8") : null;
  if (current === content) continue;
  if (CHECK) stale.push(file);
  else {
    mkdirSync(p(file, ".."), { recursive: true });
    writeFileSync(p(file), content);
    console.log(`wrote ${file}`);
  }
}
if (CHECK && stale.length) {
  console.error(`Out of date: ${stale.join(", ")}. Run: node scripts/build.mjs`);
  process.exit(1);
}
console.log(`${entries.length} entries, ${plugins.length} installable plugins in "${mk}".`);
